### PR TITLE
Multiple scanner and documentation

### PR DESCRIPTION
**Pull request by aurore-finco**
Hello!

I did further work on this plugin, adding new functions and a documentation. Everything is tested in our lab with pymodaq 4.
- The PLcounter was not much changed
- I added move plugins to control a piezo scanner. There are 2 of them:
    - ScannerControl, which was a first attempt. It is working for standalone use but not really for scanning. I left it there as it can be an example for other users.
    - MultipleScannerControl, which allows me to use several scanners to perform scans without conflicts in use of the resources of the NI card. 
  These scanner plugins are meant for slow and careful movement inside our atomic force microscope, meaning that timing the movement is really important. For this reason, a clock channel is shared between the different scanners through a specific controller which I added in a new file in the hardware folder, `daqmx_objects.py`. To achieve this, one of them is set as Master and the others as Slaves.
- I wrote a documentation with sphinx about all this, and about how to create more move or viewer plugins based on NI cards. It can be found in the folder `docs`. Where and how should it be published?

### CODE REVIEW

**Comment by seb5g** [comment]
Hi,
thanks for the work. i went quickly through the documentation and I think it will be useful but I guess some basic understanding of the DAQmx object should be given. As for where to publish this, I dig a bit and found this:

https://coderefinery.github.io/documentation/gh_workflow/

basically we could automatically compile your doc on a github server, serve it onto a dedicated branch and publish the built documentation on the repo github page. Then from the main pymodaq documentation, we could add the link to that documentation from a dedicated plugin documentation. Want to try to set it on your repo as a test?

**Comment by aurore-finco** [comment]
Hi!
Yes, you are right, I will add some info about the DAQmx objects. 
I'm going to try to publish the documentation on my repo, sure.

**Comment by aurore-finco** [comment]
Hello!
I updated the docs to explain a few things about the DAQmx objects, and modified the README because many people were fooled to think that this plugin was plug-and-play, whereas you need to create your own daq_move or daq_viewer to use it.
The docs publication works fine on my repo, so if you modify the settings as below it should work here too: 
image

**Review by seb5g — APPROVED** [review]

**Comment by seb5g** [comment]
Thx for the work 
I added a link to the doc in the main doc page
I'll publish a release asap

**Pull request merged**
